import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { apiGet, apiPost } from "@/lib/api";
import type { ActionResponse, ApprovalSummary, Department, UserPublic } from "@/lib/types";
import { Check, ClipboardCheck, ShieldCheck, X } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { PageHeader, Panel } from "@/components/PortalLayout";
import { EmptyState } from "./Dashboard";

export default function Approvals() {
  const client = useQueryClient(); const [teams, setTeams] = useState<Record<string, string[]>>({});
  const { data: actor } = useQuery({ queryKey: ["me"], queryFn: () => apiGet<UserPublic>("/auth/me") });
  const { data: requests = [], isLoading } = useQuery({ queryKey: ["approvals"], queryFn: () => apiGet<ApprovalSummary[]>("/admin/approvals") });
  const { data: departments = [] } = useQuery({ queryKey: ["departments"], queryFn: () => apiGet<Department[]>("/departments") });
  const act = useMutation({ mutationFn: ({ id, action }: { id: string; action: "approve" | "decline" }) => apiPost<ActionResponse>(`/admin/approvals/${id}`, { action, department_ids: action === "approve" ? (teams[id] ?? []) : null }), onSuccess: (result) => { toast.success(result.message); void client.invalidateQueries({ queryKey: ["approvals"] }); void client.invalidateQueries({ queryKey: ["dashboard"] }); }, onError: () => toast.error("Request could not be processed") });
  const toggle = (requestId: string, departmentId: string) => { const current = teams[requestId] ?? []; setTeams({ ...teams, [requestId]: current.includes(departmentId) ? current.filter((id) => id !== departmentId) : [...current, departmentId] }); };
  return <div data-testid="approvals-page"><PageHeader eyebrow="Blind approval desk" title="Access requests" description="Approve people without exposing company records. You can only grant teams already assigned to your role." />
    <Panel data-testid="approval-policy-panel" className="mb-5 border-cyan-400/20"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 size-5 text-cyan-300" /><div><p data-testid="approval-role-summary" className="text-sm font-semibold text-slate-100">{actor?.role === "admin" ? "Admin approval-only mode" : `${actor?.role === "pro_admin" ? "Pro Admin" : "Owner"} approval controls`}</p><p className="mt-1 text-xs leading-5 text-slate-500">Choose one, several, or all available teams before approving. Admins cannot open files, records, or user management.</p></div></div></Panel>
    <Panel data-testid="approval-queue-panel"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-heading text-lg font-semibold text-slate-100">Pending queue</h2><p data-testid="approval-count" className="mt-1 text-xs text-slate-500">{requests.length} requests waiting</p></div><ClipboardCheck className="size-5 text-cyan-300" /></div>{isLoading ? <p data-testid="approvals-loading" className="py-10 text-center text-xs text-slate-500">Loading requests…</p> : requests.length === 0 ? <EmptyState testId="approvals-empty" icon={<ClipboardCheck />} title="No pending requests" copy="New account requests will appear here automatically." /> : <div className="space-y-3">{requests.map((request, index) => { const selected = teams[request.id] ?? []; return <div data-testid={`approval-row-${index}`} key={request.id} className="rounded-xl border border-slate-800 bg-slate-950/50 p-4"><div className="flex flex-wrap items-center gap-3"><div className="min-w-0 flex-1"><p className="font-semibold text-slate-200">{request.name}</p><p className="text-xs text-slate-500">{request.email}</p></div><Button data-testid={`approval-all-teams-button-${index}`} variant="outline" size="sm" onClick={() => setTeams({ ...teams, [request.id]: departments.map((d) => d.id) })}>All my teams</Button><Button data-testid={`approval-confirm-button-${index}`} size="sm" disabled={!selected.length || act.isPending} onClick={() => act.mutate({ id: request.id, action: "approve" })} className="bg-emerald-400 text-slate-950 hover:bg-emerald-300"><Check className="mr-1 size-3.5" />Approve</Button><Button data-testid={`approval-decline-button-${index}`} variant="destructive" size="sm" onClick={() => act.mutate({ id: request.id, action: "decline" })}><X className="mr-1 size-3.5" />Decline</Button></div><div className="mt-4 flex flex-wrap gap-2">{departments.map((department) => <label data-testid={`approval-${index}-team-${department.id}`} key={department.id} className={`cursor-pointer rounded-full border px-3 py-1.5 text-[11px] ${selected.includes(department.id) ? "border-cyan-400/50 bg-cyan-400/10 text-cyan-300" : "border-slate-700 text-slate-500"}`}><input type="checkbox" className="sr-only" checked={selected.includes(department.id)} onChange={() => toggle(request.id, department.id)} />{department.name}</label>)}</div></div>; })}</div>}</Panel>
  </div>;
}