import { Link } from "react-router-dom";
import type { ReactNode } from "react";
import { useQuery } from "@tanstack/react-query";
import { apiGet } from "@/lib/api";
import type { DashboardStats } from "@/lib/types";
import { ArrowUpRight, Database, FileText, FolderKanban, Search, ShieldCheck, Users } from "lucide-react";
import { PageHeader, Panel } from "@/components/PortalLayout";

export default function Dashboard() {
  const { data, isError, isLoading } = useQuery({ queryKey: ["dashboard"], queryFn: () => apiGet<DashboardStats>("/dashboard"), staleTime: 30_000 });
  const stats = data ?? { total_records: 0, active_departments: 0, active_users: 0, pending_requests: 0, recent_files: [], department_breakdown: [] };
  const cards = [["Total records", stats.total_records.toLocaleString(), Database, "text-cyan-300"], ["Active departments", stats.active_departments, FolderKanban, "text-blue-300"], ["Active users", stats.active_users, Users, "text-emerald-300"], ["Pending requests", stats.pending_requests, ShieldCheck, "text-amber-300"]] as const;
  return <div data-testid="dashboard-page"><PageHeader eyebrow="Workspace overview" title="Dashboard" description="A fast, focused read on the data and access activity your team cares about." action={<Link data-testid="dashboard-search-cta" to="/search" className="inline-flex h-10 items-center justify-center gap-2 rounded-lg bg-cyan-400 px-4 text-sm font-semibold text-slate-950 hover:bg-cyan-300"><Search className="size-4" />Search records</Link>} />
    {isError && <div data-testid="dashboard-error-banner" className="mb-5 rounded-xl border border-amber-400/30 bg-amber-400/10 p-4 text-sm text-amber-200">Live metrics are temporarily unavailable. Your workspace shell is still ready.</div>}
    <div data-testid="dashboard-stats-grid" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, Icon, color]) => <Panel key={label} className="relative overflow-hidden"><div className={`absolute -right-4 -top-4 size-20 rounded-full blur-2xl ${color.replace("text-", "bg-")}/10`} /><div className="flex items-start justify-between"><p data-testid={`metric-${label.toLowerCase().replaceAll(" ", "-")}-label`} className="text-xs font-medium text-slate-400">{label}</p><Icon className={`size-5 ${color}`} /></div><p data-testid={`metric-${label.toLowerCase().replaceAll(" ", "-")}-value`} className="mt-6 font-heading text-3xl font-bold tracking-tight text-slate-100">{isLoading ? "—" : value}</p><p className="mt-1 text-[11px] text-slate-500">Updated from indexed workspace data</p></Panel>)}</div>
    <div className="mt-5 grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><Panel data-testid="department-breakdown-panel"><div className="mb-5 flex items-center justify-between"><div><h2 data-testid="department-breakdown-title" className="font-heading text-lg font-semibold text-slate-100">Department activity</h2><p className="mt-1 text-xs text-slate-500">Record distribution across your active scopes</p></div><Link data-testid="dashboard-departments-link" to="/departments" className="text-xs text-cyan-300 hover:text-cyan-200">Manage <ArrowUpRight className="ml-1 inline size-3" /></Link></div>{stats.department_breakdown.length === 0 ? <EmptyState testId="department-breakdown-empty" icon={<FolderKanban />} title="No department data yet" copy="Create a department, then upload a CSV to see activity here." /> : <div data-testid="department-breakdown-list" className="space-y-4">{stats.department_breakdown.slice(0, 6).map((d, index) => <div data-testid={`department-breakdown-row-${index}`} key={d.department_id}><div className="mb-2 flex justify-between text-xs"><span className="text-slate-300">{d.name}</span><span className="font-mono text-slate-500">{d.count.toLocaleString()}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-cyan-400" style={{ width: `${Math.min(100, Math.max(5, (d.count / Math.max(stats.total_records, 1)) * 100))}%` }} /></div></div>)}</div>}</Panel>
      <Panel data-testid="recent-files-panel"><div className="mb-5 flex items-center justify-between"><div><h2 data-testid="recent-files-title" className="font-heading text-lg font-semibold text-slate-100">Recent files</h2><p className="mt-1 text-xs text-slate-500">Latest persisted uploads</p></div><FileText className="size-5 text-cyan-300" /></div>{stats.recent_files.length === 0 ? <EmptyState testId="recent-files-empty" icon={<FileText />} title="No uploads yet" copy="Your file history will appear here." /> : <div data-testid="recent-files-list" className="space-y-3">{stats.recent_files.map((file, index) => <div data-testid={`recent-file-row-${index}`} key={file.id} className="flex items-center gap-3 rounded-xl border border-slate-800 bg-slate-950/50 p-3"><span className="grid size-9 place-items-center rounded-lg bg-cyan-400/10 text-cyan-300"><FileText className="size-4" /></span><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium text-slate-200">{file.name}</p><p className="mt-1 text-[10px] text-slate-500">{file.row_count.toLocaleString()} rows · {file.department_name}</p></div><Link data-testid={`recent-file-link-${index}`} to="/files" className="text-slate-500 hover:text-cyan-300"><ArrowUpRight className="size-4" /></Link></div>)}</div>}</Panel></div>
    <div data-testid="quick-actions" className="mt-5 grid gap-4 md:grid-cols-3"><QuickAction href="/search" icon={<Search />} title="Instant search" copy="Find records across every permitted field." testId="quick-search-card" /><QuickAction href="/files" icon={<FileText />} title="Upload a CSV" copy="Persist a file and skip duplicate rows automatically." testId="quick-upload-card" /><QuickAction href="/users" icon={<Users />} title="Manage access" copy="Keep users and department permissions current." testId="quick-users-card" /></div>
  </div>;
}
function QuickAction({ href, icon, title, copy, testId }: { href: string; icon: ReactNode; title: string; copy: string; testId: string }) { return <Link data-testid={testId} to={href} className="group rounded-2xl border border-slate-800 bg-slate-900/50 p-5 hover:border-cyan-400/40 hover:bg-slate-900"><div className="mb-5 flex size-10 items-center justify-center rounded-xl bg-slate-800 text-cyan-300 transition-colors group-hover:bg-cyan-400/10">{icon}</div><p className="font-semibold text-slate-100">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{copy}</p></Link>; }
export function EmptyState({ testId, icon, title, copy }: { testId: string; icon: ReactNode; title: string; copy: string }) { return <div data-testid={testId} className="grid place-items-center rounded-xl border border-dashed border-slate-800 px-6 py-10 text-center"><div className="mb-3 text-slate-600">{icon}</div><p data-testid={`${testId}-title`} className="text-sm font-medium text-slate-300">{title}</p><p data-testid={`${testId}-copy`} className="mt-1 max-w-xs text-xs text-slate-500">{copy}</p></div>; }