import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { apiPost, apiGet } from "@/lib/api";
import type { ActionResponse, Department, UserPublic } from "@/lib/types";
import { FolderKanban, Plus, Trash2, Users as UsersIcon } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { PageHeader, Panel } from "@/components/PortalLayout";
import { EmptyState } from "./Dashboard";

export default function Departments() {
  const client = useQueryClient(); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [selected, setSelected] = useState<string[]>([]);
  const { data: user } = useQuery({ queryKey: ["me"], queryFn: () => apiGet<UserPublic>("/auth/me") }); const { data: departments = [], isLoading } = useQuery({ queryKey: ["departments"], queryFn: () => apiGet<Department[]>("/departments") });
  const create = useMutation({ mutationFn: () => apiPost<Department>("/departments", { name, description }), onSuccess: () => { toast.success("Team created and added to your access"); setName(""); setDescription(""); void client.invalidateQueries({ queryKey: ["departments"] }); void client.invalidateQueries({ queryKey: ["me"] }); }, onError: () => toast.error("Only Owner or Pro Admin can create teams") });
  const remove = useMutation({ mutationFn: () => apiPost<ActionResponse>("/departments/bulk-delete", selected), onSuccess: (r) => { toast.success(r.message); setSelected([]); void client.invalidateQueries({ queryKey: ["departments"] }); void client.invalidateQueries({ queryKey: ["dashboard"] }); }, onError: () => toast.error("Unable to delete selected departments") });
  const manager = user?.role === "owner" || user?.role === "pro_admin"; const deletable = user?.role === "owner" ? departments : departments.filter((d) => d.created_by === user?.id); const allSelected = deletable.length > 0 && deletable.every((d) => selected.includes(d.id));
  return <div data-testid="departments-page"><PageHeader eyebrow="Scoped access silos" title="Departments" description="Create clean team boundaries, see activity, and manage only the scopes allowed to your role." action={manager ? <Button data-testid="create-department-cta" onClick={() => document.getElementById("department-create-form")?.scrollIntoView({ behavior: "smooth" })} className="bg-cyan-400 text-slate-950 hover:bg-cyan-300"><Plus className="mr-2 size-4" />New team</Button> : undefined} />
    {manager && <Panel data-testid="department-create-panel" className="mb-5"><form id="department-create-form" data-testid="department-create-form" onSubmit={(e) => { e.preventDefault(); create.mutate(); }} className="grid gap-3 md:grid-cols-[1fr_1.4fr_auto]"><Input data-testid="department-name-input" value={name} onChange={(e) => setName(e.target.value)} placeholder="Team name" required className="border-slate-700 bg-slate-950" /><Textarea data-testid="department-description-input" value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Short description (optional)" className="min-h-10 border-slate-700 bg-slate-950" /><Button data-testid="save-department-button" type="submit" disabled={create.isPending} className="bg-cyan-400 text-slate-950 hover:bg-cyan-300">{create.isPending ? "Saving…" : "Create team"}</Button></form></Panel>}
    <Panel data-testid="departments-list-panel"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 data-testid="departments-list-title" className="font-heading text-lg font-semibold text-slate-100">Team directory</h2><p data-testid="departments-count" className="mt-1 text-xs text-slate-500">{departments.length} visible scopes</p></div>{manager && deletable.length > 0 && <div className="flex items-center gap-3"><label className="flex items-center gap-2 text-xs text-slate-400"><input data-testid="department-select-all-checkbox" type="checkbox" checked={allSelected} onChange={() => setSelected(allSelected ? [] : deletable.map((d) => d.id))} /> Select deletable</label>{selected.length > 0 && <Button data-testid="bulk-delete-departments-button" variant="destructive" size="sm" onClick={() => remove.mutate()}>Delete {selected.length}</Button>}</div>}</div>{isLoading ? <div data-testid="departments-loading-state" className="py-10 text-center text-xs text-slate-500">Loading teams…</div> : departments.length === 0 ? <EmptyState testId="departments-empty-state" icon={<FolderKanban />} title="No teams yet" copy="Create your first team to start assigning uploads and users." /> : <div data-testid="department-card-grid" className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{departments.map((d, index) => { const canDelete = user?.role === "owner" || d.created_by === user?.id; return <div data-testid={`department-card-${index}`} key={d.id} className="relative rounded-xl border border-slate-800 bg-slate-950/50 p-4 hover:border-cyan-400/30">{canDelete && <input data-testid={`department-select-checkbox-${index}`} type="checkbox" checked={selected.includes(d.id)} onChange={() => setSelected(selected.includes(d.id) ? selected.filter((id) => id !== d.id) : [...selected, d.id])} className="absolute right-4 top-4" />}<div className="mb-4 grid size-10 place-items-center rounded-xl bg-cyan-400/10 text-cyan-300"><FolderKanban className="size-5" /></div><h3 data-testid={`department-name-${index}`} className="font-semibold text-slate-100">{d.name}</h3><p data-testid={`department-description-${index}`} className="mt-1 min-h-10 text-xs leading-5 text-slate-500">{d.description || "No description added."}</p><div className="mt-5 flex gap-4 border-t border-slate-800 pt-3 text-[11px] text-slate-500"><span><strong data-testid={`department-record-count-${index}`} className="font-mono text-slate-300">{d.record_count}</strong> records</span><span className="flex items-center gap-1"><UsersIcon className="size-3" /><strong data-testid={`department-user-count-${index}`} className="font-mono text-slate-300">{d.user_count}</strong> users</span></div></div>; })}</div>}</Panel>
  </div>;
}