import { useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { apiDelete, apiDownload, apiGet, apiUpload } from "@/lib/api";
import type { ActionResponse, Department, FileAsset, FileUploadResponse, UserPublic } from "@/lib/types";
import { Download, FileCheck2, FileText, RefreshCw, Trash2, UploadCloud } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { PageHeader, Panel } from "@/components/PortalLayout";
import { EmptyState } from "./Dashboard";

export default function Files() {
  const client = useQueryClient(); const input = useRef<HTMLInputElement>(null); const [department, setDepartment] = useState(""); const [reuploadId, setReuploadId] = useState<string | null>(null); const [uploading, setUploading] = useState(false);
  const { data: user } = useQuery({ queryKey: ["me"], queryFn: () => apiGet<UserPublic>("/auth/me") }); const { data: departments = [] } = useQuery({ queryKey: ["departments"], queryFn: () => apiGet<Department[]>("/departments") }); const { data: files = [], isLoading } = useQuery({ queryKey: ["files"], queryFn: () => apiGet<FileAsset[]>("/files"), staleTime: 15_000 });
  const mutation = useMutation({ mutationFn: async (file: File) => { if (!department && !reuploadId) throw new Error("Choose a department first"); const form = new FormData(); form.append("file", file); if (!reuploadId) form.append("department_id", department); setUploading(true); return apiUpload<FileUploadResponse>(reuploadId ? `/files/${reuploadId}/reupload` : "/files/upload", form); }, onSuccess: (result) => { toast.success(result.message); setReuploadId(null); void client.invalidateQueries({ queryKey: ["files"] }); void client.invalidateQueries({ queryKey: ["dashboard"] }); if (input.current) input.current.value = ""; }, onError: (error: Error) => toast.error(error.message || "Upload failed"), onSettled: () => setUploading(false) });
  const deleteMutation = useMutation({ mutationFn: (id: string) => apiDelete<ActionResponse>(`/files/${id}`), onSuccess: (r) => { toast.success(r.message); void client.invalidateQueries({ queryKey: ["files"] }); void client.invalidateQueries({ queryKey: ["dashboard"] }); }, onError: () => toast.error("Only the owner can delete files") });
  const handleFile = (file?: File) => { if (file) mutation.mutate(file); };
  const download = async (file: FileAsset) => { try { const blob = await apiDownload(`/files/${file.id}/download`); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = file.name; anchor.click(); URL.revokeObjectURL(url); toast.success("Download started"); } catch { toast.error("Unable to download this file"); } };
  return <div data-testid="files-page"><PageHeader eyebrow="Persistent data intake" title="Files" description="Upload CSVs into a department silo, review history, and keep original files available for download or re-upload." action={<Button data-testid="choose-file-button" onClick={() => input.current?.click()} className="bg-cyan-400 text-slate-950 hover:bg-cyan-300"><UploadCloud className="mr-2 size-4" />Choose CSV</Button>} />
    <input data-testid="file-upload-input" ref={input} type="file" accept=".csv,text/csv" className="hidden" onChange={(e) => handleFile(e.target.files?.[0])} />
    <Panel data-testid="upload-panel" className="mb-5"><div className="grid gap-5 lg:grid-cols-[1fr_280px]"><button data-testid="upload-dropzone" onClick={() => input.current?.click()} className="group rounded-2xl border border-dashed border-slate-700 bg-slate-950/60 px-6 py-10 text-center hover:border-cyan-400/60 hover:bg-cyan-400/[.03]"><span className="mx-auto mb-4 grid size-12 place-items-center rounded-2xl bg-cyan-400/10 text-cyan-300"><UploadCloud className="size-6" /></span><p data-testid="upload-dropzone-title" className="font-medium text-slate-200">Drop a CSV here or browse files</p><p data-testid="upload-dropzone-copy" className="mt-2 text-xs text-slate-500">UTF-8 CSV · up to 15 MB · duplicate rows are skipped</p>{uploading && <div data-testid="upload-progress" className="mx-auto mt-5 max-w-xs"><div className="mb-2 flex justify-between text-[10px] text-cyan-300"><span>Processing and saving</span><span>Working…</span></div><div className="h-1.5 overflow-hidden rounded-full bg-slate-800"><div className="h-full w-2/3 animate-pulse rounded-full bg-cyan-400" /></div></div>}</button><div className="rounded-2xl border border-slate-800 bg-slate-950/60 p-5"><label data-testid="upload-department-field" className="text-xs font-medium text-slate-400">Save to department<select data-testid="upload-department-select" value={department} onChange={(e) => setDepartment(e.target.value)} className="mt-2 h-10 w-full rounded-lg border border-slate-700 bg-slate-900 px-3 text-sm text-slate-200"><option value="">Choose a scope</option>{departments.map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</select></label><div data-testid="upload-speed-note" className="mt-6 border-t border-slate-800 pt-4 text-xs leading-5 text-slate-500"><FileCheck2 className="mb-2 size-4 text-emerald-400" /><p>Original file and upload summary stay attached to the history record.</p></div></div></div></Panel>
    <Panel data-testid="file-history-panel"><div className="mb-5 flex items-center justify-between"><div><h2 data-testid="file-history-title" className="font-heading text-lg font-semibold text-slate-100">Upload history</h2><p data-testid="file-history-count" className="mt-1 text-xs text-slate-500">{files.length} persisted {files.length === 1 ? "file" : "files"}</p></div><FileText className="size-5 text-cyan-300" /></div>{isLoading || files.length === 0 ? (isLoading ? <div data-testid="files-loading-state" className="py-10 text-center text-xs text-slate-500">Loading file history…</div> : <EmptyState testId="files-empty-state" icon={<FileText />} title="No files saved yet" copy="Choose a department and upload your first CSV." />) : <div data-testid="file-history-table" className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-b border-slate-800 text-[10px] uppercase tracking-wider text-slate-500"><tr><th className="py-3">File</th><th className="px-3">Scope</th><th className="px-3">Rows</th><th className="px-3">Uploaded</th><th className="px-3 text-right">Actions</th></tr></thead><tbody>{files.map((file, index) => <tr data-testid={`file-row-${index}`} key={file.id} className="border-b border-slate-800/70"><td className="py-4"><div className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-lg bg-slate-800 text-cyan-300"><FileText className="size-4" /></span><div><p data-testid={`file-name-${index}`} className="max-w-48 truncate font-medium text-slate-200">{file.name}</p><p data-testid={`file-summary-${index}`} className="mt-1 text-[10px] text-slate-500">{file.inserted_count} added · {file.skipped_count} skipped</p></div></div></td><td className="px-3 text-cyan-300">{file.department_name}</td><td className="px-3 font-mono text-slate-300">{file.row_count.toLocaleString()}</td><td className="px-3 text-slate-500">{new Date(file.uploaded_at).toLocaleDateString()}</td><td className="px-3"><div className="flex justify-end gap-1"><Button data-testid={`download-file-button-${index}`} variant="ghost" size="icon-xs" onClick={() => void download(file)} title="Download"><Download className="size-3.5" /></Button><Button data-testid={`reupload-file-button-${index}`} variant="ghost" size="icon-xs" onClick={() => { setReuploadId(file.id); setDepartment(file.department_id); input.current?.click(); }} title="Re-upload"><RefreshCw className="size-3.5" /></Button>{user?.role === "owner" && <Button data-testid={`delete-file-button-${index}`} variant="ghost" size="icon-xs" onClick={() => deleteMutation.mutate(file.id)} className="text-red-300 hover:text-red-200" title="Delete"><Trash2 className="size-3.5" /></Button>}</div></td></tr>)}</tbody></table></div>}</Panel>
  </div>;
}