import { useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ApiError, apiDelete, apiDownload, apiGet, apiPost, apiUpload } from "@/lib/api";
import type { ActionResponse, Department, FileAsset, UploadSession, UserPublic } from "@/lib/types";
import { Download, FileCheck2, FileText, RefreshCw, Trash2, UploadCloud } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { PageHeader, Panel } from "@/components/PortalLayout";
import { EmptyState } from "./Dashboard";

export default function Files() {
  const client = useQueryClient(); const input = useRef<HTMLInputElement>(null); const [department, setDepartment] = useState(""); const [reuploadId, setReuploadId] = useState<string | null>(null); const [uploading, setUploading] = useState(false); const [progress, setProgress] = useState(0); const [stage, setStage] = useState(""); const [selectedFiles, setSelectedFiles] = useState<string[]>([]);
  const { data: user } = useQuery({ queryKey: ["me"], queryFn: () => apiGet<UserPublic>("/auth/me") }); const { data: departments = [] } = useQuery({ queryKey: ["departments"], queryFn: () => apiGet<Department[]>("/departments") }); const { data: files = [], isLoading } = useQuery({ queryKey: ["files"], queryFn: () => apiGet<FileAsset[]>("/files"), staleTime: 15_000 });
  const mutation = useMutation({ mutationFn: async (file: File) => { if (!department && !reuploadId) throw new Error("Choose a department first"); if (file.size > 1024 * 1024 * 1024) throw new Error("CSV must be 1 GB or smaller"); setUploading(true); setProgress(0); setStage("Starting secure upload"); const chunkSize = 4 * 1024 * 1024; const totalChunks = Math.ceil(file.size / chunkSize); const session = await apiPost<UploadSession>("/uploads/init", { filename: file.name, size_bytes: file.size, department_id: department, total_chunks: totalChunks, replace_file_id: reuploadId }); let nextIndex = 0; let uploaded = 0; const worker = async () => { while (nextIndex < totalChunks) { const index = nextIndex++; const form = new FormData(); form.append("chunk", file.slice(index * chunkSize, Math.min(file.size, (index + 1) * chunkSize)), `${file.name}.part-${index}`); await apiUpload<UploadSession>(`/uploads/${session.id}/chunks/${index}`, form); uploaded += 1; setProgress(Math.round((uploaded / totalChunks) * 68)); setStage(`Uploading chunk ${uploaded} of ${totalChunks}`); } }; await Promise.all(Array.from({ length: Math.min(4, totalChunks) }, () => worker())); setStage("Indexing rows in the background"); await apiPost<UploadSession>(`/uploads/${session.id}/complete`); for (let attempt = 0; attempt < 900; attempt += 1) { await new Promise((resolve) => setTimeout(resolve, 2000)); const status = await apiGet<UploadSession>(`/uploads/${session.id}`); setProgress(status.progress); setStage(status.message); if (status.status === "complete") return status; if (status.status === "failed") throw new Error(status.message || "CSV processing failed"); } throw new Error("Processing is taking longer than expected; it will continue in the background"); }, onSuccess: (result) => { toast.success(result.message); setReuploadId(null); setProgress(100); void client.invalidateQueries({ queryKey: ["files"] }); void client.invalidateQueries({ queryKey: ["dashboard"] }); if (input.current) input.current.value = ""; }, onError: (error: Error) => { const detail = error instanceof ApiError && error.body && typeof error.body === "object" && "detail" in error.body ? String((error.body as { detail: unknown }).detail) : error.message; toast.error(detail || "Upload failed"); }, onSettled: () => setUploading(false) });
  const deleteMutation = useMutation({ mutationFn: (id: string) => apiDelete<ActionResponse>(`/files/${id}`), onSuccess: (r) => { toast.success(r.message); void client.invalidateQueries({ queryKey: ["files"] }); void client.invalidateQueries({ queryKey: ["dashboard"] }); }, onError: () => toast.error("You can only delete files in your managed teams") });
  const bulkDeleteMutation = useMutation({ mutationFn: (ids: string[]) => apiPost<ActionResponse>("/files/bulk-delete", ids), onSuccess: (r) => { toast.success(r.message); setSelectedFiles([]); void client.invalidateQueries({ queryKey: ["files"] }); void client.invalidateQueries({ queryKey: ["dashboard"] }); }, onError: () => toast.error("Unable to delete selected files") });
  const handleFile = (file?: File) => { if (file) mutation.mutate(file); };
  const download = async (file: FileAsset) => { try { const blob = await apiDownload(`/files/${file.id}/download`); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = file.name; anchor.click(); URL.revokeObjectURL(url); toast.success("Download started"); } catch { toast.error("Unable to download this file"); } };
  const proAdminTools = user?.role === "pro_admin" && files.length > 0 ? <Panel data-testid="pro-admin-bulk-file-actions" className="mb-5"><div className="flex flex-wrap items-center gap-3"><label className="flex items-center gap-2 text-xs text-slate-300"><input data-testid="pro-admin-file-select-all-checkbox" type="checkbox" checked={selectedFiles.length === files.length} onChange={() => setSelectedFiles(selectedFiles.length === files.length ? [] : files.map((file) => file.id))} />Select all managed files</label><span className="text-xs text-slate-500">{selectedFiles.length} selected</span><Button data-testid="pro-admin-delete-selected-files-button" variant="destructive" size="sm" disabled={!selectedFiles.length || bulkDeleteMutation.isPending} onClick={() => bulkDeleteMutation.mutate(selectedFiles)}>Delete selected with records</Button></div><div className="mt-3 flex flex-wrap gap-2">{files.map((file, index) => <label data-testid={`pro-admin-file-checkbox-${index}`} key={file.id} className="rounded-lg border border-slate-800 px-3 py-2 text-xs text-slate-400"><input type="checkbox" checked={selectedFiles.includes(file.id)} onChange={() => setSelectedFiles(selectedFiles.includes(file.id) ? selectedFiles.filter((id) => id !== file.id) : [...selectedFiles, file.id])} className="mr-2" />{file.name}</label>)}</div></Panel> : null;
  return <div data-testid="files-page"><PageHeader eyebrow="Persistent data intake" title="Files" description="Upload CSVs into a department silo, review history, and keep original files available for download or re-upload." action={<Button data-testid="choose-file-button" onClick={() => input.current?.click()} className="bg-cyan-400 text-slate-950 hover:bg-cyan-300"><UploadCloud className="mr-2 size-4" />Choose CSV</Button>} />
    <input data-testid="file-upload-input" ref={input} type="file" accept=".csv,text/csv" className="hidden" onChange={(e) => handleFile(e.target.files?.[0])} />
    {proAdminTools}
    <Panel data-testid="upload-panel" className="mb-5"><div className="grid gap-5 lg:grid-cols-[1fr_280px]"><button data-testid="upload-dropzone" onClick={() => input.current?.click()} className="group rounded-2xl border border-dashed border-slate-700 bg-slate-950/60 px-6 py-10 text-center hover:border-cyan-400/60 hover:bg-cyan-400/[.03]"><span className="mx-auto mb-4 grid size-12 place-items-center rounded-2xl bg-cyan-400/10 text-cyan-300"><UploadCloud className="size-6" /></span><p data-testid="upload-dropzone-title" className="font-medium text-slate-200">Drop a CSV here or browse files</p><p data-testid="upload-dropzone-copy" className="mt-2 text-xs text-slate-500">Resumable 4 MB chunks · files up to 1 GB · background indexing</p>{uploading && <div data-testid="upload-progress" className="mx-auto mt-5 max-w-sm"><div className="mb-2 flex justify-between text-[10px] text-cyan-300"><span>{stage}</span><span data-testid="upload-progress-value">{progress}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-cyan-400 transition-[width] duration-300" style={{ width: `${progress}%` }} /></div></div>}</button><div className="rounded-2xl border border-slate-800 bg-slate-950/60 p-5"><label data-testid="upload-department-field" className="text-xs font-medium text-slate-400">Save to department<select data-testid="upload-department-select" value={department} onChange={(e) => setDepartment(e.target.value)} className="mt-2 h-10 w-full rounded-lg border border-slate-700 bg-slate-900 px-3 text-sm text-slate-200"><option value="">Choose a scope</option>{departments.map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</select></label><div data-testid="upload-speed-note" className="mt-6 border-t border-slate-800 pt-4 text-xs leading-5 text-slate-500"><FileCheck2 className="mb-2 size-4 text-emerald-400" /><p>Uploads continue through small reliable requests, then index in the background.</p></div></div></div></Panel>
    {user?.role === "owner" && files.length > 0 && <Panel data-testid="bulk-file-actions" className="mb-5"><div className="flex flex-wrap items-center gap-3"><label className="flex items-center gap-2 text-xs text-slate-300"><input data-testid="file-select-all-checkbox" type="checkbox" checked={selectedFiles.length === files.length} onChange={() => setSelectedFiles(selectedFiles.length === files.length ? [] : files.map((file) => file.id))} />Select all files</label><span data-testid="selected-file-count" className="text-xs text-slate-500">{selectedFiles.length} selected</span><Button data-testid="delete-selected-files-button" variant="destructive" size="sm" disabled={!selectedFiles.length || bulkDeleteMutation.isPending} onClick={() => bulkDeleteMutation.mutate(selectedFiles)}>Delete selected with records</Button><Button data-testid="delete-all-files-button" variant="outline" size="sm" disabled={bulkDeleteMutation.isPending} onClick={() => bulkDeleteMutation.mutate(files.map((file) => file.id))}>Delete all files</Button></div><div className="mt-3 flex flex-wrap gap-2">{files.map((file, index) => <label data-testid={`bulk-file-checkbox-${index}`} key={file.id} className={`cursor-pointer rounded-lg border px-3 py-2 text-xs ${selectedFiles.includes(file.id) ? "border-cyan-400/50 bg-cyan-400/10 text-cyan-300" : "border-slate-800 text-slate-500"}`}><input type="checkbox" checked={selectedFiles.includes(file.id)} onChange={() => setSelectedFiles(selectedFiles.includes(file.id) ? selectedFiles.filter((id) => id !== file.id) : [...selectedFiles, file.id])} className="mr-2" />{file.name}</label>)}</div></Panel>}
    <Panel data-testid="file-history-panel"><div className="mb-5 flex items-center justify-between"><div><h2 data-testid="file-history-title" className="font-heading text-lg font-semibold text-slate-100">Upload history</h2><p data-testid="file-history-count" className="mt-1 text-xs text-slate-500">{files.length} persisted {files.length === 1 ? "file" : "files"}</p></div><FileText className="size-5 text-cyan-300" /></div>{isLoading || files.length === 0 ? (isLoading ? <div data-testid="files-loading-state" className="py-10 text-center text-xs text-slate-500">Loading file history…</div> : <EmptyState testId="files-empty-state" icon={<FileText />} title="No files saved yet" copy="Choose a department and upload your first CSV." />) : <div data-testid="file-history-table" className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-b border-slate-800 text-[10px] uppercase tracking-wider text-slate-500"><tr><th className="py-3">File</th><th className="px-3">Scope</th><th className="px-3">Rows</th><th className="px-3">Uploaded</th><th className="px-3 text-right">Actions</th></tr></thead><tbody>{files.map((file, index) => <tr data-testid={`file-row-${index}`} key={file.id} className="border-b border-slate-800/70"><td className="py-4"><div className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-lg bg-slate-800 text-cyan-300"><FileText className="size-4" /></span><div><p data-testid={`file-name-${index}`} className="max-w-48 truncate font-medium text-slate-200">{file.name}</p><p data-testid={`file-summary-${index}`} className="mt-1 text-[10px] text-slate-500">{file.inserted_count} added · {file.skipped_count} skipped</p></div></div></td><td className="px-3 text-cyan-300">{file.department_name}</td><td className="px-3 font-mono text-slate-300">{file.row_count.toLocaleString()}</td><td className="px-3 text-slate-500">{new Date(file.uploaded_at).toLocaleDateString()}</td><td className="px-3"><div className="flex justify-end gap-1"><Button data-testid={`download-file-button-${index}`} variant="ghost" size="icon-xs" onClick={() => void download(file)} title="Download"><Download className="size-3.5" /></Button><Button data-testid={`reupload-file-button-${index}`} variant="ghost" size="icon-xs" onClick={() => { setReuploadId(file.id); setDepartment(file.department_id); input.current?.click(); }} title="Re-upload"><RefreshCw className="size-3.5" /></Button>{user?.role === "owner" && <Button data-testid={`delete-file-button-${index}`} variant="ghost" size="icon-xs" onClick={() => deleteMutation.mutate(file.id)} className="text-red-300 hover:text-red-200" title="Delete"><Trash2 className="size-3.5" /></Button>}</div></td></tr>)}</tbody></table></div>}</Panel>
  </div>;
}