import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { apiGet, apiPost } from "@/lib/api";
import type { ActionResponse, BulkLookupResponse, Department, RecordSearchResponse, UserPublic } from "@/lib/types";
import { ListFilter, Search as SearchIcon, Upload, X } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { PageHeader, Panel } from "@/components/PortalLayout";
import { EmptyState } from "./Dashboard";

export default function Search() {
  const client = useQueryClient(); const [q, setQ] = useState(""); const [debouncedQ, setDebouncedQ] = useState(""); const [department, setDepartment] = useState(""); const [page, setPage] = useState(1); const [tab, setTab] = useState<"search" | "bulk">("search"); const [bulk, setBulk] = useState(""); const [selected, setSelected] = useState<string[]>([]);
  const { data: user } = useQuery({ queryKey: ["me"], queryFn: () => apiGet<UserPublic>("/auth/me") });
  const { data: departments = [] } = useQuery({ queryKey: ["departments"], queryFn: () => apiGet<Department[]>("/departments") });
  useEffect(() => { const timer = window.setTimeout(() => setDebouncedQ(q), 250); return () => window.clearTimeout(timer); }, [q]);
  const search = useQuery({ queryKey: ["records", debouncedQ, department, page], queryFn: () => apiGet<RecordSearchResponse>(`/search?q=${encodeURIComponent(debouncedQ)}&department_id=${encodeURIComponent(department)}&page=${page}&page_size=25`), staleTime: 10_000, enabled: tab === "search" && !!user && (user.role !== "user" || debouncedQ.trim().length >= 3) });
  const bulkLookup = useMutation({ mutationFn: () => apiPost<BulkLookupResponse>("/search/bulk", { query: bulk, department_id: department || null }), onError: () => toast.error("Bulk lookup failed") });
  const deleteMutation = useMutation({ mutationFn: () => apiPost<ActionResponse>("/search/bulk-delete", selected), onSuccess: (r) => { toast.success(r.message); setSelected([]); void client.invalidateQueries({ queryKey: ["records"] }); }, onError: () => toast.error("You do not have permission to delete records") });
  const privacyLocked = user?.role === "user" && (q.trim().length < 3 || q.trim() !== debouncedQ.trim()); const rows = privacyLocked ? [] : (search.data?.items ?? []); const displayedTotal = privacyLocked ? 0 : (search.data?.total ?? 0); const allSelected = rows.length > 0 && rows.every((row) => selected.includes(row.id)); const toggleAll = () => { if (allSelected) setSelected(selected.filter((id) => !rows.some((row) => row.id === id))); else setSelected([...new Set([...selected, ...rows.map((row) => row.id)])]); }; const canManage = user?.role === "owner" || user?.role === "pro_admin";
  return <div data-testid="search-page" data-user-role={user?.role ?? "loading"}><PageHeader eyebrow="Indexed workspace data" title="Search records" description={user?.role === "user" ? "Your privacy is protected: no records appear until you search with at least 3 characters." : "Search across every permitted field or paste a list for a fast bulk lookup."} action={canManage ? <a data-testid="search-upload-cta" href="/files" className="inline-flex h-10 items-center gap-2 rounded-lg border border-slate-700 px-4 text-sm text-slate-200 hover:border-cyan-400/40 hover:text-cyan-300"><Upload className="size-4" />Upload data</a> : undefined} />
    <div data-testid="search-tabs" className="mb-4 flex gap-1 rounded-xl border border-slate-800 bg-slate-900/50 p-1"><button data-testid="search-tab-button" onClick={() => setTab("search")} className={`rounded-lg px-4 py-2 text-xs font-semibold ${tab === "search" ? "bg-cyan-400 text-slate-950" : "text-slate-400 hover:text-slate-100"}`}>Global search</button><button data-testid="bulk-lookup-tab-button" onClick={() => setTab("bulk")} className={`rounded-lg px-4 py-2 text-xs font-semibold ${tab === "bulk" ? "bg-cyan-400 text-slate-950" : "text-slate-400 hover:text-slate-100"}`}>Bulk lookup</button></div>
    {privacyLocked && <div data-testid="normal-user-privacy-notice" className="mb-4 rounded-xl border border-cyan-400/20 bg-cyan-400/5 p-4 text-sm text-cyan-100">Private search mode is active. Enter at least 3 characters or digits; only matching records will be revealed.</div>}
    {tab === "search" ? <Panel data-testid="search-results-panel"><div className="flex flex-col gap-3 lg:flex-row"><div className="relative flex-1"><SearchIcon className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-500" /><Input data-testid="record-search-input" value={q} onChange={(e) => { setQ(e.target.value); setPage(1); }} placeholder="Search names, phone numbers, emails, or any field…" className="h-11 border-slate-700 bg-slate-950 pl-10" />{q && <button data-testid="clear-search-button" onClick={() => setQ("")} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-500 hover:text-slate-200"><X className="size-4" /></button>}</div><select data-testid="search-department-filter" value={department} onChange={(e) => { setDepartment(e.target.value); setPage(1); }} className="h-11 rounded-lg border border-slate-700 bg-slate-950 px-3 text-sm text-slate-300"><option value="">All permitted departments</option>{departments.map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</select></div>
      <div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-y border-slate-800 py-3"><div className="flex items-center gap-3 text-xs text-slate-500"><ListFilter className="size-4 text-cyan-300" /><span data-testid="search-result-count">{displayedTotal} matches</span>{selected.length > 0 && <span data-testid="selected-record-count" className="rounded-full bg-cyan-400/10 px-2 py-1 text-cyan-300">{selected.length} selected</span>}</div>{selected.length > 0 && <div className="flex gap-2"><Button data-testid="clear-record-selection-button" variant="ghost" size="sm" onClick={() => setSelected([])}>Clear</Button><Button data-testid="bulk-delete-records-button" variant="destructive" size="sm" onClick={() => deleteMutation.mutate()}>Delete selected</Button></div>}</div>
      {rows.length === 0 ? <div className="py-6"><EmptyState testId="search-empty-state" icon={<SearchIcon />} title={search.isLoading ? "Searching your workspace…" : "No records found"} copy={search.isLoading ? "Results will appear as soon as the index responds." : "Try a different phrase or upload a CSV to start building your index."} /></div> : <div data-testid="search-results-table" className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-b border-slate-800 text-[10px] uppercase tracking-wider text-slate-500"><tr><th className="w-10 py-3"><input data-testid="record-select-all-checkbox" type="checkbox" checked={allSelected} onChange={toggleAll} /></th>{(search.data?.fields ?? []).slice(0, 5).map((field) => <th data-testid={`record-column-${field}`} key={field} className="px-3 py-3">{field}</th>)}<th className="px-3 py-3">Department</th><th className="px-3 py-3">File</th></tr></thead><tbody>{rows.map((row, index) => <tr data-testid={`record-row-${index}`} key={row.id} className="border-b border-slate-800/70 hover:bg-slate-800/40"><td className="py-3"><input data-testid={`record-select-checkbox-${index}`} type="checkbox" checked={selected.includes(row.id)} onChange={() => setSelected(selected.includes(row.id) ? selected.filter((id) => id !== row.id) : [...selected, row.id])} /></td>{(search.data?.fields ?? []).slice(0, 5).map((field) => <td data-testid={`record-cell-${index}-${field}`} key={field} className="max-w-48 truncate px-3 py-3 font-mono text-slate-300">{row.data[field] || "—"}</td>)}<td className="px-3 py-3 text-cyan-300">{row.department_name}</td><td className="px-3 py-3 text-slate-500">{row.file_name}</td></tr>)}</tbody></table></div>}
      <div data-testid="search-pagination" className="mt-4 flex items-center justify-between text-xs text-slate-500"><span>Page {page} of {Math.max(1, Math.ceil(displayedTotal / 25))}</span><div className="flex gap-2"><Button data-testid="previous-page-button" variant="outline" size="sm" disabled={page === 1} onClick={() => setPage(page - 1)}>Previous</Button><Button data-testid="next-page-button" variant="outline" size="sm" disabled={page >= Math.ceil(displayedTotal / 25)} onClick={() => setPage(page + 1)}>Next</Button></div></div></Panel> : <Panel data-testid="bulk-lookup-panel"><div className="max-w-2xl"><h2 data-testid="bulk-lookup-title" className="font-heading text-lg font-semibold text-slate-100">Look up many values at once</h2><p data-testid="bulk-lookup-description" className="mt-1 text-xs leading-5 text-slate-500">Paste one phone number, name, or identifier per line. Company Database checks up to 500 values against your permitted records.</p><Textarea data-testid="bulk-lookup-input" value={bulk} onChange={(e) => setBulk(e.target.value)} placeholder={"+1 555 0100\n+1 555 0101\nJordan Lee"} className="mt-5 min-h-48 border-slate-700 bg-slate-950" /><div className="mt-4 flex items-center gap-3"><Button data-testid="run-bulk-lookup-button" onClick={() => bulkLookup.mutate()} disabled={!bulk.trim() || bulkLookup.isPending} className="bg-cyan-400 text-slate-950 hover:bg-cyan-300">{bulkLookup.isPending ? "Looking up…" : "Run bulk lookup"}</Button>{bulkLookup.data && <span data-testid="bulk-lookup-summary" className="text-xs text-emerald-300">{bulkLookup.data.matched_queries} of {bulkLookup.data.total_queries} values matched</span>}</div></div>{bulkLookup.data && <div data-testid="bulk-lookup-results" className="mt-7 overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-b border-slate-800 text-[10px] uppercase text-slate-500"><tr><th className="py-3">Match</th><th className="px-3">Department</th><th className="px-3">File</th></tr></thead><tbody>{bulkLookup.data.items.map((row, index) => <tr data-testid={`bulk-result-row-${index}`} key={row.id} className="border-b border-slate-800/70"><td className="py-3 font-mono text-slate-200">{Object.values(row.data).slice(0, 2).join(" · ")}</td><td className="px-3 text-cyan-300">{row.department_name}</td><td className="px-3 text-slate-500">{row.file_name}</td></tr>)}</tbody></table></div>}</Panel>}
  </div>;
}