import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { apiGet, apiPost, apiPut } from "@/lib/api";
import type { ActionResponse, BrandSettings, UserPublic } from "@/lib/types";
import { Image, KeyRound, Save, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { PageHeader, Panel } from "@/components/PortalLayout";

const defaultLabels = { dashboard: "Dashboard", search: "Search", files: "Files", departments: "Departments", users: "Users" };

export default function SettingsV2() {
  const client = useQueryClient();
  const { data: user } = useQuery({ queryKey: ["me"], queryFn: () => apiGet<UserPublic>("/auth/me") });
  const { data: brand } = useQuery({ queryKey: ["branding"], queryFn: () => apiGet<BrandSettings>("/branding") });
  const [companyName, setCompanyName] = useState("Company Database"); const [logo, setLogo] = useState<string | null>(null); const [labels, setLabels] = useState<Record<string, string>>(defaultLabels);
  const [current, setCurrent] = useState(""); const [next, setNext] = useState(""); const [confirm, setConfirm] = useState("");
  useEffect(() => { if (brand) { setCompanyName(brand.company_name); setLogo(brand.logo_data_url ?? null); setLabels({ ...defaultLabels, ...brand.nav_labels }); } }, [brand]);
  const saveBrand = useMutation({ mutationFn: () => apiPut<BrandSettings>("/branding", { company_name: companyName, logo_data_url: logo, nav_labels: labels }), onSuccess: (result) => { client.setQueryData(["branding"], result); toast.success("Brand and navigation saved"); }, onError: () => toast.error("Brand settings could not be saved") });
  const change = useMutation({ mutationFn: () => apiPost<ActionResponse>("/auth/change-password", { current_password: current, new_password: next }), onSuccess: (r) => { toast.success(r.message); setCurrent(""); setNext(""); setConfirm(""); }, onError: () => toast.error("Password could not be updated") });
  const chooseLogo = (file?: File) => { if (!file) return; if (file.size > 2 * 1024 * 1024) { toast.error("Logo must be smaller than 2 MB"); return; } const reader = new FileReader(); reader.onload = () => setLogo(String(reader.result)); reader.readAsDataURL(file); };
  return <div data-testid="settings-page"><PageHeader eyebrow="Owner control center" title="Settings" description="Edit the company identity, navigation labels, logo, and account security from one place." />
    {user?.role === "owner" && <Panel data-testid="branding-settings-panel" className="mb-5"><div className="mb-5 flex items-center gap-3"><span className="grid size-10 place-items-center overflow-hidden rounded-xl bg-cyan-400/10 text-cyan-300">{logo ? <img src={logo} alt="Logo preview" className="size-full object-cover" /> : <Image className="size-5" />}</span><div><h2 data-testid="branding-settings-title" className="font-heading text-lg font-semibold text-slate-100">Company branding</h2><p className="text-xs text-slate-500">Changes update the login screen and navigation automatically.</p></div></div><div className="grid gap-4 lg:grid-cols-2"><label className="text-xs text-slate-400">Company name<Input data-testid="company-name-input" value={companyName} maxLength={40} onChange={(e) => setCompanyName(e.target.value)} className="mt-2 border-slate-700 bg-slate-950" /></label><label className="text-xs text-slate-400">Company logo<input data-testid="company-logo-input" type="file" accept="image/png,image/jpeg,image/webp" onChange={(e) => chooseLogo(e.target.files?.[0])} className="mt-2 block w-full rounded-lg border border-slate-700 bg-slate-950 p-2 text-xs" /></label></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{Object.keys(defaultLabels).map((key) => <label key={key} className="text-[10px] uppercase tracking-wide text-slate-500">{key}<Input data-testid={`nav-label-${key}-input`} value={labels[key] ?? ""} onChange={(e) => setLabels({ ...labels, [key]: e.target.value })} className="mt-2 border-slate-700 bg-slate-950 text-xs normal-case" /></label>)}</div><div className="mt-5 flex gap-2"><Button data-testid="save-branding-button" onClick={() => saveBrand.mutate()} disabled={saveBrand.isPending} className="bg-cyan-400 text-slate-950 hover:bg-cyan-300"><Save className="mr-2 size-4" />Save all branding</Button>{logo && <Button data-testid="remove-logo-button" variant="outline" onClick={() => setLogo(null)}>Remove logo</Button>}</div></Panel>}
    <div className="grid gap-5 lg:grid-cols-[1fr_360px]"><Panel data-testid="change-password-panel"><div className="mb-6 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-cyan-400/10 text-cyan-300"><KeyRound className="size-5" /></span><div><h2 data-testid="change-password-title" className="font-heading text-lg font-semibold text-slate-100">Change password</h2><p className="text-xs text-slate-500">Use at least 8 characters and avoid reusing old passwords.</p></div></div><form data-testid="change-password-form" onSubmit={(e) => { e.preventDefault(); if (next !== confirm) { toast.error("New passwords do not match"); return; } change.mutate(); }} className="max-w-lg space-y-4"><label className="block text-xs text-slate-400">Current password<Input data-testid="current-password-input" required type="password" value={current} onChange={(e) => setCurrent(e.target.value)} className="mt-2 border-slate-700 bg-slate-950" /></label><label className="block text-xs text-slate-400">New password<Input data-testid="settings-new-password-input" required minLength={8} type="password" value={next} onChange={(e) => setNext(e.target.value)} className="mt-2 border-slate-700 bg-slate-950" /></label><label className="block text-xs text-slate-400">Confirm new password<Input data-testid="confirm-password-input" required minLength={8} type="password" value={confirm} onChange={(e) => setConfirm(e.target.value)} className="mt-2 border-slate-700 bg-slate-950" /></label><Button data-testid="change-password-button" type="submit" disabled={change.isPending} className="bg-cyan-400 text-slate-950 hover:bg-cyan-300">{change.isPending ? "Updating…" : "Update password"}</Button></form></Panel><Panel data-testid="session-security-panel"><ShieldCheck className="size-6 text-emerald-300" /><h2 data-testid="session-security-title" className="mt-4 font-heading text-lg font-semibold text-slate-100">Session security</h2><p data-testid="session-security-copy" className="mt-2 text-sm leading-6 text-slate-500">Signed in as <span className="text-slate-300">{user?.email}</span>. Your role controls every visible action.</p><div className="mt-6 border-t border-slate-800 pt-4 text-xs text-slate-500"><p>Role</p><p data-testid="settings-role-value" className="mt-1 uppercase text-cyan-300">{user?.role}</p></div></Panel></div>
  </div>;
}