import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { apiGet, apiPost } from "@/lib/api";
import type { ActionResponse, UserPublic } from "@/lib/types";
import { KeyRound, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { PageHeader, Panel } from "@/components/PortalLayout";

export default function Settings() {
  const { data: user } = useQuery({ queryKey: ["me"], queryFn: () => apiGet<UserPublic>("/auth/me") }); const [current, setCurrent] = useState(""); const [next, setNext] = useState(""); const [confirm, setConfirm] = useState("");
  const change = useMutation({ mutationFn: () => apiPost<ActionResponse>("/auth/change-password", { current_password: current, new_password: next }), onSuccess: (r) => { toast.success(r.message); setCurrent(""); setNext(""); setConfirm(""); }, onError: () => toast.error("Password could not be updated") });
  return <div data-testid="settings-page"><PageHeader eyebrow="Workspace preferences" title="Settings" description="Keep your account secure and review the access context for this session." /><div className="grid gap-5 lg:grid-cols-[1fr_360px]"><Panel data-testid="change-password-panel"><div className="mb-6 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-cyan-400/10 text-cyan-300"><KeyRound className="size-5" /></span><div><h2 data-testid="change-password-title" className="font-heading text-lg font-semibold text-slate-100">Change password</h2><p className="text-xs text-slate-500">Use at least 8 characters and avoid reusing old passwords.</p></div></div><form data-testid="change-password-form" onSubmit={(e) => { e.preventDefault(); if (next !== confirm) { toast.error("New passwords do not match"); return; } change.mutate(); }} className="max-w-lg space-y-4"><label className="block text-xs text-slate-400">Current password<Input data-testid="current-password-input" required type="password" value={current} onChange={(e) => setCurrent(e.target.value)} className="mt-2 border-slate-700 bg-slate-950" /></label><label className="block text-xs text-slate-400">New password<Input data-testid="settings-new-password-input" required minLength={8} type="password" value={next} onChange={(e) => setNext(e.target.value)} className="mt-2 border-slate-700 bg-slate-950" /></label><label className="block text-xs text-slate-400">Confirm new password<Input data-testid="confirm-password-input" required minLength={8} type="password" value={confirm} onChange={(e) => setConfirm(e.target.value)} className="mt-2 border-slate-700 bg-slate-950" /></label><Button data-testid="change-password-button" type="submit" disabled={change.isPending} className="bg-cyan-400 text-slate-950 hover:bg-cyan-300">{change.isPending ? "Updating…" : "Update password"}</Button></form></Panel><Panel data-testid="session-security-panel"><ShieldCheck className="size-6 text-emerald-300" /><h2 data-testid="session-security-title" className="mt-4 font-heading text-lg font-semibold text-slate-100">Session security</h2><p data-testid="session-security-copy" className="mt-2 text-sm leading-6 text-slate-500">You are signed in as <span className="text-slate-300">{user?.email}</span>. Sessions use an httpOnly cookie and are cleared when you sign out.</p><div className="mt-6 border-t border-slate-800 pt-4 text-xs text-slate-500"><p>Role</p><p data-testid="settings-role-value" className="mt-1 uppercase text-cyan-300">{user?.role}</p></div></Panel></div></div>;
}